// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChsgGY30uhZKkavY2ATLGO7Q1TVhGqdwc',
    appId: '1:535806692554:android:8cc9167a18000f75263833',
    messagingSenderId: '535806692554',
    projectId: 'fyplauncher-f7cf9',
    storageBucket: 'fyplauncher-f7cf9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm46dJ9nnq3gBvxXxZP_0rUF3HRlM3SVg',
    appId: '1:535806692554:web:f5679851d36b18f8263833',
    messagingSenderId: '535806692554',
    projectId: 'fyplauncher-f7cf9',
    authDomain: 'fyplauncher-f7cf9.firebaseapp.com',
    storageBucket: 'fyplauncher-f7cf9.firebasestorage.app',
    measurementId: 'G-KLKCQ834K5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOcDhl81H20QlA3PifKlBItzug9g_dROA',
    appId: '1:535806692554:ios:4a51bfc53bf1ede9263833',
    messagingSenderId: '535806692554',
    projectId: 'fyplauncher-f7cf9',
    storageBucket: 'fyplauncher-f7cf9.firebasestorage.app',
    iosBundleId: 'com.syafril.fyplauncher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOcDhl81H20QlA3PifKlBItzug9g_dROA',
    appId: '1:535806692554:ios:4a51bfc53bf1ede9263833',
    messagingSenderId: '535806692554',
    projectId: 'fyplauncher-f7cf9',
    storageBucket: 'fyplauncher-f7cf9.firebasestorage.app',
    iosBundleId: 'com.syafril.fyplauncher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm46dJ9nnq3gBvxXxZP_0rUF3HRlM3SVg',
    appId: '1:535806692554:web:c82549038cbbc933263833',
    messagingSenderId: '535806692554',
    projectId: 'fyplauncher-f7cf9',
    authDomain: 'fyplauncher-f7cf9.firebaseapp.com',
    storageBucket: 'fyplauncher-f7cf9.firebasestorage.app',
    measurementId: 'G-GNJ57YBCZS',
  );
}
